### ISSUE TITLE
Generate Avery labels for children

### ISSUE THREAD

**Issue by aeewhite** [TreeTopper/TreeTopper#45]
One of our requirements is to generate printable labels for children to be placed on the Angel Tree tags

These tags will carry the generic information about a child and should be printed onto a sheet matching the layout of common commercial label sheets

**Comment by jzarob** [comment]
Can you pick which Avery form label we're looking for?

**Comment by aeewhite** [comment]
Sure, let me go look at them

**Comment by aeewhite** [comment]
How about these: [Avery 5160](http://www.avery.com/avery/en_us/Products/Labels/Addressing-Labels/Easy-Peel-White-Address-Labels_05160.htm)? I think they would probably be big enough for a single child's info each

**Comment by jzarob** [comment]
I think they need to be slightly larger than that. Just because it has to show their name, id, sizes and wish. which is why I used the 5164 model

**Comment by aeewhite** [comment]
Oh, forgot that angel tree tags are actually specific to the kids. Yeah, we probably need larger ones

**Comment by aeewhite** [comment]
Okay, so Avery has like a billion labels (of which I'm sure some of are kinda hard to find irl). I propose we take a field trip to a store and see which label sizes are readily available and pick one from those.

**Comment by jzarob** [comment]
@aeewhite field trip tomorrow during our productive day of madness that's slated for tomorrow
