### ISSUE TITLE
Sorting for family view

### ISSUE THREAD

**Issue by jzarob** [TreeTopper/TreeTopper#51]
Allow table to be sorted by the header columns on the family index page.

**Comment by aeewhite** [comment]
What sorts do you think would be helpful?

**Comment by jzarob** [comment]
I would imagine all of them. Just do it in JS is my vote.

**Comment by jzarob** [comment]
We could probably use DataTables and make our lives super easy. We could also then get rid of the mongo search on the server side and just return the giant list of families for the year.

**Comment by aeewhite** [comment]
This sounds a like a great idea if the result of it is still pretty. You wanna do it @jzarob?
